version: '3.8'

services:
  neo4j:
    # Docker image to be used
    image: neo4j:5.16.0-enterprise

    # Hostname
    hostname: neo4j-db

    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"
    
    # Volumes
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
      
    # Passes the following environment variables to the container
    environment:
      - NEO4J_AUTH=neo4j/terra123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes